language: objective-c
osx_image: xcode8.2

before_install:
  - carthage bootstrap --verbose

script:
  - open -a "simulator" --args -CurrentDeviceUDID AD8E8C76-910E-437D-88C2-4D6F6EBE3355
  - xcodebuild clean build test -project SwiftyJSONModel.xcodeproj -scheme SwiftyJSONModel -destination 'platform=iOS Simulator,name=iPhone 6'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
